// =============================================================
// Automatically generated file - Do not modify it manually
// Generated by NNEDataGenerator.py
// =============================================================
#pragma once
#include "CoreMinimal.h"
#include "NNEDataRecords.generated.h"

// Serialization interface that all records must be implement
struct INNEDataRecord
{
	virtual FString Serialize() const = 0; 
	virtual ~INNEDataRecord() = default;
}

{% for record in parser.records %}
USTRUCT(BlueprintType)
struct {{ record.struct_name }} : public INNEDataRecord
{
	GENERATED_BODY()
	
{% for field in record.fields %}
	UPROPERTY(BlueprintReadWrite, Category="NNE|Data")
	{{ field.type_name }} {{ field.field_name }};
{% endfor %}
};

{% endfor %}
